global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'ansible-webhook'

receivers:
- name: 'ansible-webhook'
  webhook_configs:
  - url: 'http://ansible-webhook:5000/alert'
    send_resolved: true
